### ISSUE TITLE
Ordinary.Core.StackFastIdPool功能缺失

### ISSUE THREAD

**Issue by F-Unction** [Erxl/Ordinary#1]
Ordinary.Core.StackFastIdPool 缺少查询某ID状态的方法

**Comment by Erxl** [comment]
之前一直以为栈实现不能知道哪个id有没有被用到，现在想了想其实可以

在栈实现情况下，Newest以内的idReturn会被存进栈里，代表此id空闲；Newest以上的id则全部空闲，故据此可判断id的状态

感谢提醒，各种池子的api会被更新，撸码中……
